services:
  mysql:
    image: mysql:8.0
    container_name: dbt_ec_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
